### PR TITLE
Added missing packages.config for NuGet deps

### PR DESCRIPTION
**Pull request by dakotahawkins**
Also updated the packages in use to the latest stable version.

### CODE REVIEW

**Comment by dakotahawkins** [comment]
I wanted to make another proposed change, but had to do this to get the solution to build without re-adding the two NuGet packages being used.

**Comment by dakotahawkins** [comment]
Ah, I made a mistake. I think the real "fix" is to move the pre-existing packages.config up to the project directory. Visual Studio doesn't seem to pick it up otherwise. Will update momentarily.

**Comment by dakotahawkins** [comment]
OK, this is just the result of moving packages.config up to the project directory and updating the nuget packages.

**Comment by Wumpf** [comment]
Thank you for these fixes! I agree with moving package.config back to where it belongs and the package updates, but what purpose serves adding IncludeToolbox/app.config ? 
I just tried a fresh checkout and it worked fine without it.

**Comment by dakotahawkins** [comment]
I'm not certain why (or if) the app.config was necessary, it was auto-generated when I moved the package.config file or maybe when I updated the packages.

I can certainly try removing it if you'd like and re-pushing!

**Comment by Wumpf** [comment]
That would be nice, thank you :)

**Comment by dakotahawkins** [comment]
Seems to build fine without the app.config. Pushed up its removal.

**Pull request merged**
